"""Aggregate standard-eval scores and write comparison table to docs/."""
from __future__ import annotations
import json
import os
from pathlib import Path

ROOT = Path("/ex_disk2/mhpark/poc/chartvr/results/standard")
OUT = Path("/ex_disk2/mhpark/poc/chartvr/docs/standard_eval_comparison.md")

MODELS = [
    "zero_shot_qwen3_5_4b", "v8_sft", "v_hq_lite_sft",
    "v9_sft", "v9_1_sft",
    "row_a_outcome", "row_b_vapv",
    "row3_dapo_outcome", "row4_dapo_vapv",
]
BENCHES = ["chartqa_human", "chartqa_augmented", "chartqa_pro", "charxiv_reasoning", "chartmuseum"]
SHORT = {"chartqa_human": "H", "chartqa_augmented": "A", "chartqa_pro": "PRO",
         "charxiv_reasoning": "CXR", "chartmuseum": "CMU"}

# Baselines from docs/v_hq_lite_eval_report.md (our OLD eval pipeline scores)
# Columns: chartqa_human, chartqa_augmented, charxiv_reasoning, chartqa_pro, chartmuseum
OLD_BASELINE = {
    "v7_zero_shot":  {"chartqa_human": 77.84, "chartqa_augmented": 86.32, "charxiv_reasoning": 45.40, "chartqa_pro": 36.09, "chartmuseum": 29.90},
    "v8_sft":        {"chartqa_human": 83.68, "chartqa_augmented": 88.64, "charxiv_reasoning": 44.50, "chartqa_pro": 35.83, "chartmuseum": 27.60},
    "v8_outcome":    {"chartqa_human": 84.48, "chartqa_augmented": 88.96, "charxiv_reasoning": 46.00, "chartqa_pro": 36.40, "chartmuseum": 28.30},
    "v8_process":    {"chartqa_human": 83.76, "chartqa_augmented": 88.96, "charxiv_reasoning": 45.30, "chartqa_pro": 36.14, "chartmuseum": 30.40},
    "v9_sft":        {"chartqa_human": 82.32, "chartqa_augmented": 91.36, "charxiv_reasoning": 42.10, "chartqa_pro": 35.11, "chartmuseum": 27.30},
    "v9_1_sft":      {"chartqa_human": 81.76, "chartqa_augmented": 87.92, "charxiv_reasoning": 39.50, "chartqa_pro": 35.99, "chartmuseum": 26.40},
    "v_hq_lite_sft": {"chartqa_human": 71.20, "chartqa_augmented": 94.16, "charxiv_reasoning": 40.80, "chartqa_pro": 27.98, "chartmuseum": 23.80},
}

# Map of new model tag → baseline key
BASELINE_MAP = {
    "zero_shot_qwen3_5_4b": "v7_zero_shot",
    "v8_sft": "v8_sft",
    "v_hq_lite_sft": "v_hq_lite_sft",
    "v9_sft": "v9_sft",
    "v9_1_sft": "v9_1_sft",
    "row_a_outcome": "v8_outcome",       # v7 Row A ≈ outcome RL family
    "row_b_vapv": "v8_process",          # v7 Row B ≈ process RL family
    "row3_dapo_outcome": "v8_outcome",
    "row4_dapo_vapv": "v8_process",
}


def score_for(model: str, mode: str, bench: str) -> float | None:
    p = ROOT / model / f"think_{mode}" / f"{bench}_scored.jsonl"
    if not p.exists():
        return None
    rs = []
    with open(p) as f:
        for line in f:
            try:
                rs.append(json.loads(line))
            except json.JSONDecodeError:
                pass
    if not rs:
        return None
    return sum(r.get("score", 0) or 0 for r in rs) / len(rs) * 100


def fmt(x):
    return f"{x:5.2f}" if x is not None else "  -- "


def fmt_delta(new, old):
    if new is None or old is None:
        return "  -- "
    d = new - old
    return f"{d:+5.2f}"


def main() -> None:
    lines: list[str] = []
    lines.append("# Standard-Protocol Eval — vs Old Eval Baselines")
    lines.append("")
    lines.append("Generated by `scripts/build_comparison_table.py`. Standard scores from "
                 "`results/standard/<model>/think_{off,on}/<bench>_scored.jsonl`. Baselines "
                 "from `docs/v_hq_lite_eval_report.md` (our pre-standard pipeline with "
                 "thinking + `<answer>` extraction).")
    lines.append("")
    lines.append("Columns: H=chartqa_human, A=chartqa_augmented, PRO=chartqa_pro, "
                 "CXR=charxiv_reasoning, CMU=chartmuseum.")
    lines.append("")
    lines.append("## Standard scores (think_off / think_on)")
    lines.append("")
    header = "| Model | mode | H | A | PRO | CXR | CMU | AVG5 |"
    sep = "|---|---|---|---|---|---|---|---|"
    lines.append(header)
    lines.append(sep)
    for m in MODELS:
        for mode in ("off", "on"):
            scores = [score_for(m, mode, b) for b in BENCHES]
            valid = [s for s in scores if s is not None]
            avg5 = sum(valid) / len(valid) if valid else None
            row = f"| {m} | {mode} | " + " | ".join(fmt(s) for s in scores) + f" | {fmt(avg5)} |"
            lines.append(row)
    lines.append("")
    lines.append("## Δ (standard − old baseline)")
    lines.append("")
    lines.append("Standard score uses **best of think_off / think_on per model** (best-mode column).")
    lines.append("")
    header2 = "| Model | best-mode | H Δ | A Δ | PRO Δ | CXR Δ | CMU Δ | AVG5 (std) | AVG5 (old) | AVG5 Δ |"
    lines.append(header2)
    lines.append("|---|---|---|---|---|---|---|---|---|---|")
    for m in MODELS:
        bk = BASELINE_MAP[m]
        old = OLD_BASELINE[bk]
        # pick best mode per bench, then compare
        best_per_bench = {}
        for b in BENCHES:
            off_s = score_for(m, "off", b)
            on_s = score_for(m, "on", b)
            cands = [(off_s, "off"), (on_s, "on")]
            cands = [c for c in cands if c[0] is not None]
            if not cands:
                best_per_bench[b] = (None, "-")
                continue
            best_per_bench[b] = max(cands, key=lambda x: x[0])
        # majority best-mode label
        modes = [best_per_bench[b][1] for b in BENCHES if best_per_bench[b][1] != "-"]
        mode_label = max(set(modes), key=modes.count) if modes else "-"
        deltas = [fmt_delta(best_per_bench[b][0], old.get(b)) for b in BENCHES]
        std_vals = [best_per_bench[b][0] for b in BENCHES]
        old_vals = [old.get(b) for b in BENCHES]
        avg_std = sum(v for v in std_vals if v is not None) / len([v for v in std_vals if v is not None]) if any(v is not None for v in std_vals) else None
        avg_old = sum(v for v in old_vals if v is not None) / len([v for v in old_vals if v is not None]) if any(v is not None for v in old_vals) else None
        avg_d = (avg_std - avg_old) if (avg_std is not None and avg_old is not None) else None
        avg_d_s = f"{avg_d:+5.2f}" if avg_d is not None else "  -- "
        lines.append(f"| {m} | {mode_label} | " + " | ".join(deltas) +
                     f" | {fmt(avg_std)} | {fmt(avg_old)} | {avg_d_s} |")
    lines.append("")
    lines.append("## Notes")
    lines.append("- Standard pipeline: vLLM `--reasoning-parser qwen3` separates `<think>` "
                 "into `reasoning_content`; scorers see only post-think `content`. ChartQA "
                 "uses LMMs-Eval `relaxed_correctness`; CharXiv/ChartMuseum use Qwen3.6-27B "
                 "judge (3-host vLLM, enable_thinking=False, official rubrics verbatim).")
    lines.append("- Old baseline pipeline: thinking on with `<answer>` regex extraction, "
                 "custom relaxed scorer (more lenient unit handling).")
    lines.append("- `mode` column shows the most-frequently-best mode across the 5 benches "
                 "for each model.")
    lines.append("- `--` indicates the scored file is missing (e.g., judge phase still in flight).")
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
